pipelines:
  default:
    - step:
        image: node:10.15.3
        name: Build and Test MDR api
        caches:
          - node
        script:
          - cd ARQSI
          - npm install
          - npm build
          - npm test
          - cd ../
    - step:
        image: mcr.microsoft.com/dotnet/sdk:5.0
        name: Build and Test MDV api
        caches:
          - dotnetcore
        script:
          - cd MDV
          - dotnet restore
          - dotnet build
          - dotnet test
          - cd ../
    - step:
        image: node:10.15.3
        name: Build and Test SPA
        caches:
          - node
        script:
          - cd SPA
          - npm install
          - npm run build
          - cd ../